name: Release & Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Maven Package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set version from tag
        run: |
          TAG_NAME=${GITHUB_REF_NAME}          # Gives only '1.0.0'
          TAG_NAME=${TAG_NAME#v}               # Removes leading 'v' if tag is like 'v1.0.0'
          echo "Setting Maven version to $TAG_NAME"
          mvn versions:set -DnewVersion=$TAG_NAME

      - name: Build
        run: mvn -B clean package -DskipTests

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode deploy -DskipTests --settings ${{ github.workspace }}/settings.xml
